sudo: required
services:
  - docker

before_install:
  - docker build -t aghabekyan374/docker-react -f Dockerfile.dev .

script:
  - docker run aghabekyan374/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-933754265105"
  bucket_path: "docker"
  on:
    branch: master


    Docker-env.6aptiqczha.us-east-2.elasticbeanstalk.com