sudo: required
services:
  - docker

before_install:
  - docker build -t aghabekyan374/docker-react -f Dockerfile.dev .

script:
  - docker run aghabekyan374/docker-react npm run test -- --coverage

  